version: "3.8"

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=proninteam_example_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:management"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.django.base
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/proninteam_example_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DEBUG=True
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: celery -A collection_project.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/proninteam_example_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DEBUG=True
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure


volumes:
  postgres_data: